package io.github.meymchen.lspf.hello;

import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Properties;

/**
 * Plugin identity generated by Gradle from {@code gradle.properties}.
 *
 * <p>Reading it here keeps {@code gradle.properties} the single place that names the
 * plugin and its bundled executable, so a renamed copy of the template stays consistent.
 */
final class ServerMetadata {
    private ServerMetadata() {}

    static String get(String key) {
        Properties values = new Properties();
        try (var input = ServerMetadata.class.getResourceAsStream("/lspf-server.properties")) {
            if (input == null) {
                throw new IllegalStateException("Missing bundled language server metadata");
            }
            values.load(new InputStreamReader(input, StandardCharsets.UTF_8));
        } catch (IOException error) {
            throw new IllegalStateException("Cannot read language server metadata", error);
        }
        String value = values.getProperty(key);
        if (value == null || value.isBlank()) {
            throw new IllegalStateException("Missing language server metadata entry: " + key);
        }
        return value;
    }
}
